apiVersion: v1
kind: ConfigMap
metadata:
  name: shelf-check-config
  namespace: cls
data:
  AWS_REGION: eu-north-1
  DB_SECRET_NAME: rds/app-db-credentials
  DB_HOST: app-rds.cv8kqom4alnf.eu-north-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: appdb