apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelf-check-app
  namespace: cls
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shelf-check
  template:
    metadata:
      labels:
        app: shelf-check
    spec:
      serviceAccountName: shelf-check-sa
      containers:
        - name: flask-app
          image: omarbaddour1/shelf-check-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: shelf-check-config
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
