apiVersion: v1
kind: Service
metadata:
  name: shelf-check-service
  namespace: cls
spec:
  type: NodePort
  selector:
    app: shelf-check
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
